<?php

return [
    'categories' => [
        [
            'id' => 1,
            'name' => 'Pizza House',
            'slug' => 'pizza-house',
            'logo' => 'images/placeholder.png',
            'brand' => 'pizza-house',
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 2,
            'name' => 'Burger Joint',
            'slug' => 'burger-joint',
            'logo' => 'images/placeholder.png',
            'brand' => 'burger-joint',
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        [
            'id' => 3,
            'name' => 'Sushi Bar',
            'slug' => 'sushi-bar',
            'logo' => 'images/placeholder.png',
            'brand' => 'sushi-bar',
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
    ],

    'types' => [
        [
            'id' => 1,
            'name' => 'Food',
            'icon' => 'utensils',
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 2,
            'name' => 'Beverage',
            'icon' => 'coffee',
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 3,
            'name' => 'Dessert',
            'icon' => 'ice-cream',
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
    ],

    'subcategories' => [
        // Pizza House - Food
        [
            'id' => 1,
            'name' => 'Classic Pizzas',
            'slug' => 'classic-pizzas',
            'category_id' => 1,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 2,
            'name' => 'Specialty Pizzas',
            'slug' => 'specialty-pizzas',
            'category_id' => 1,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Burger Joint - Food
        [
            'id' => 3,
            'name' => 'Classic Burgers',
            'slug' => 'classic-burgers',
            'category_id' => 2,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        [
            'id' => 4,
            'name' => 'Gourmet Burgers',
            'slug' => 'gourmet-burgers',
            'category_id' => 2,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        
        // Sushi Bar - Food
        [
            'id' => 5,
            'name' => 'Sushi Rolls',
            'slug' => 'sushi-rolls',
            'category_id' => 3,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        [
            'id' => 6,
            'name' => 'Sashimi',
            'slug' => 'sashimi',
            'category_id' => 3,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        
        // Shared subcategories
        [
            'id' => 7,
            'name' => 'Soft Drinks',
            'slug' => 'soft-drinks',
            'category_id' => null,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 8,
            'name' => 'Smoothies',
            'slug' => 'smoothies',
            'category_id' => null,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 11,
            'name' => 'Sides & Appetizers',
            'slug' => 'sides-appetizers',
            'category_id' => null,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Shared Desserts
        [
            'id' => 9,
            'name' => 'Cakes & Pastries',
            'slug' => 'cakes-pastries',
            'category_id' => null,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 10,
            'name' => 'Ice Cream',
            'slug' => 'ice-cream',
            'category_id' => null,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
    ],

    'items' => [
        // Pizza House - Classic Pizzas
        [
            'id' => 1,
            'name' => 'Margherita',
            'description' => 'Classic tomato, mozzarella, and basil',
            'price' => 12.99,
            'currency' => 'USD',
            'image' => 'images/items/Margherita.png',
            'is_active' => true,
            'category_id' => 1,
            'subcategory_id' => 1,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 2,
            'name' => 'Pepperoni',
            'description' => 'Loaded with pepperoni and cheese',
            'price' => 14.99,
            'currency' => 'USD',
            'image' => 'images/items/Pepperoni.png',
            'is_active' => true,
            'category_id' => 1,
            'subcategory_id' => 1,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Pizza House - Specialty Pizzas
        [
            'id' => 3,
            'name' => 'BBQ Chicken Pizza',
            'description' => 'BBQ sauce, grilled chicken, red onions',
            'price' => 16.99,
            'currency' => 'USD',
            'image' => 'images/items/BBQ Chicken Pizza.png',
            'is_active' => true,
            'category_id' => 1,
            'subcategory_id' => 2,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 4,
            'name' => 'Four Cheese Pizza',
            'description' => 'Mozzarella, parmesan, gorgonzola, and ricotta',
            'price' => 17.99,
            'currency' => 'USD',
            'image' => 'images/items/Four Cheese Pizza.png',
            'is_active' => true,
            'category_id' => 1,
            'subcategory_id' => 2,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Burger Joint - Classic Burgers
        [
            'id' => 5,
            'name' => 'Mini Burgers',
            'description' => 'Three slider burgers with cheese and special sauce',
            'price' => 10.99,
            'currency' => 'USD',
            'image' => 'images/items/Mini Burgers.png',
            'is_active' => true,
            'category_id' => 2,
            'subcategory_id' => 3,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        [
            'id' => 6,
            'name' => 'Club Sandwich',
            'description' => 'Triple-decker with turkey, bacon, lettuce, tomato',
            'price' => 12.99,
            'currency' => 'USD',
            'image' => 'images/items/Club Sandwich.png',
            'is_active' => true,
            'category_id' => 2,
            'subcategory_id' => 3,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        
        // Burger Joint - Gourmet Burgers
        [
            'id' => 7,
            'name' => 'Chicken Wrap',
            'description' => 'Grilled chicken with fresh vegetables in a tortilla wrap',
            'price' => 11.99,
            'currency' => 'USD',
            'image' => 'images/items/Chicken Wrap.png',
            'is_active' => true,
            'category_id' => 2,
            'subcategory_id' => 4,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        [
            'id' => 8,
            'name' => 'Chicken Tenders',
            'description' => 'Crispy chicken tenders with dipping sauce',
            'price' => 13.99,
            'currency' => 'USD',
            'image' => 'images/items/Chicken Tenders.png',
            'is_active' => true,
            'category_id' => 2,
            'subcategory_id' => 4,
            'type_id' => 1,
            'created_at' => '2026-01-02 10:00:00',
            'updated_at' => '2026-01-02 10:00:00',
        ],
        
        // Sushi Bar - Sushi Rolls
        [
            'id' => 9,
            'name' => 'California Roll',
            'description' => 'Crab, avocado, cucumber',
            'price' => 8.99,
            'currency' => 'USD',
            'image' => 'images/items/California Roll.png',
            'is_active' => true,
            'category_id' => 3,
            'subcategory_id' => 5,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        [
            'id' => 10,
            'name' => 'Tuna Roll',
            'description' => 'Fresh tuna with rice and nori',
            'price' => 9.99,
            'currency' => 'USD',
            'image' => 'images/items/Tuna Roll.png',
            'is_active' => true,
            'category_id' => 3,
            'subcategory_id' => 5,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        
        // Sushi Bar - Sashimi
        [
            'id' => 11,
            'name' => 'Salmon Roll',
            'description' => 'Fresh salmon with avocado',
            'price' => 10.99,
            'currency' => 'USD',
            'image' => 'images/items/Salmon Roll.png',
            'is_active' => true,
            'category_id' => 3,
            'subcategory_id' => 5,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        [
            'id' => 12,
            'name' => 'Philadelphia Roll',
            'description' => 'Salmon, cream cheese, cucumber',
            'price' => 11.99,
            'currency' => 'USD',
            'image' => 'images/items/Philadelphia Roll.png',
            'is_active' => true,
            'category_id' => 3,
            'subcategory_id' => 5,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        
        // Shared Beverages - Soft Drinks
        [
            'id' => 13,
            'name' => 'Coca Cola',
            'description' => 'Classic cola',
            'price' => 2.99,
            'currency' => 'USD',
            'image' => 'images/items/Coca Cola.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 7,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 14,
            'name' => 'Pepsi',
            'description' => 'Refreshing cola drink',
            'price' => 2.99,
            'currency' => 'USD',
            'image' => 'images/items/pepsi.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 7,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 15,
            'name' => 'Fanta',
            'description' => 'Orange flavored soda',
            'price' => 2.99,
            'currency' => 'USD',
            'image' => 'images/items/fanta.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 7,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 16,
            'name' => 'Water',
            'description' => 'Refreshing bottled water',
            'price' => 1.99,
            'currency' => 'USD',
            'image' => 'images/items/water.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 7,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Shared Beverages - Smoothies
        [
            'id' => 17,
            'name' => 'Mango Smoothie',
            'description' => 'Fresh mango blended smoothie',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Mango Smoothie.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 8,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 18,
            'name' => 'Strawberry Smoothie',
            'description' => 'Fresh strawberry blended smoothie',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Strawberry Smoothie.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 8,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 19,
            'name' => 'Banana Smoothie',
            'description' => 'Creamy banana smoothie',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Banana Smoothie.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 8,
            'type_id' => 2,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Shared Desserts - Cakes & Pastries
        [
            'id' => 20,
            'name' => 'Chocolate Cake',
            'description' => 'Rich chocolate layer cake',
            'price' => 6.99,
            'currency' => 'USD',
            'image' => 'images/items/Chocolate Cake.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 9,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 21,
            'name' => 'Cheesecake',
            'description' => 'Creamy New York style cheesecake',
            'price' => 7.99,
            'currency' => 'USD',
            'image' => 'images/items/Cheesecake.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 9,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 22,
            'name' => 'Brownie',
            'description' => 'Fudgy chocolate brownie',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Brownie.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 9,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 23,
            'name' => 'Waffles',
            'description' => 'Belgian waffles with syrup and cream',
            'price' => 7.99,
            'currency' => 'USD',
            'image' => 'images/items/Waffles.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 9,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Shared Desserts - Ice Cream
        [
            'id' => 24,
            'name' => 'Ice Cream',
            'description' => 'Choice of vanilla, chocolate, or strawberry',
            'price' => 4.99,
            'currency' => 'USD',
            'image' => 'images/items/Ice Cream.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 10,
            'type_id' => 3,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Shared Sides & Appetizers
        [
            'id' => 25,
            'name' => 'Cheese Fries',
            'description' => 'Golden fries with melted cheese',
            'price' => 6.99,
            'currency' => 'USD',
            'image' => 'images/items/Cheese Fries.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 26,
            'name' => 'Loaded Fries',
            'description' => 'Fries topped with cheese, bacon, and sour cream',
            'price' => 8.99,
            'currency' => 'USD',
            'image' => 'images/items/Loaded Fries.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 27,
            'name' => 'Spicy Fries',
            'description' => 'Crispy fries with spicy seasoning',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Spicy Fries.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 28,
            'name' => 'Onion Rings',
            'description' => 'Crispy fried onion rings',
            'price' => 5.99,
            'currency' => 'USD',
            'image' => 'images/items/Onion Rings.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 29,
            'name' => 'Garlic Bread',
            'description' => 'Toasted bread with garlic butter',
            'price' => 4.99,
            'currency' => 'USD',
            'image' => 'images/items/Garlic Bread.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 30,
            'name' => 'Potato Skins',
            'description' => 'Crispy potato skins with cheese and bacon',
            'price' => 7.99,
            'currency' => 'USD',
            'image' => 'images/items/Potato Skins.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Additional Pizza Options
        [
            'id' => 31,
            'name' => 'Vegetarian Pizza',
            'description' => 'Fresh vegetables with mozzarella',
            'price' => 15.99,
            'currency' => 'USD',
            'image' => 'images/items/Vegetarian Pizza.png',
            'is_active' => true,
            'category_id' => 1,
            'subcategory_id' => 2,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        
        // Additional Sushi Options
        [
            'id' => 32,
            'name' => 'Mixed Roll',
            'description' => 'Assorted sushi rolls platter',
            'price' => 16.99,
            'currency' => 'USD',
            'image' => 'images/items/Mixed Roll.png',
            'is_active' => true,
            'category_id' => 3,
            'subcategory_id' => 5,
            'type_id' => 1,
            'created_at' => '2026-01-03 10:00:00',
            'updated_at' => '2026-01-03 10:00:00',
        ],
        
        // Additional Meat Options
        [
            'id' => 33,
            'name' => 'Grilled Chicken',
            'description' => 'Marinated grilled chicken breast',
            'price' => 14.99,
            'currency' => 'USD',
            'image' => 'images/items/Grilled Chicken.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 34,
            'name' => 'Beef Steak',
            'description' => 'Premium beef steak cooked to perfection',
            'price' => 24.99,
            'currency' => 'USD',
            'image' => 'images/items/Beef Steak.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 35,
            'name' => 'Lamb Chops',
            'description' => 'Tender lamb chops with herbs',
            'price' => 28.99,
            'currency' => 'USD',
            'image' => 'images/items/Lamb Chops.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
        [
            'id' => 36,
            'name' => 'Mixed Grill',
            'description' => 'Assorted grilled meats platter',
            'price' => 32.99,
            'currency' => 'USD',
            'image' => 'images/items/Mixed Grill.png',
            'is_active' => true,
            'category_id' => null,
            'subcategory_id' => 11,
            'type_id' => 1,
            'created_at' => '2026-01-01 10:00:00',
            'updated_at' => '2026-01-01 10:00:00',
        ],
    ],
];
